Add skipEmpty parameter to Serialize methods
skbkontur/Catalogue.XmlSerializer pull request #1
Opened 2019-06-27 07:54 UTC by fakefeik

2019-07-24 09:27 UTC, sivukhin requested changes

2019-07-24 09:27 UTC, sivukhin commented on Catalogue.XmlSerializer/Writing/ContentWriters/ValueWriterBase.cs
> +            WriteNonNullableValue(value, writer);
Вроде бы этот `if` тут просто так нельзя убрать. Сейчас попытка сериализовать класс с поляшкой типа `Dictionary` равной `null` свалится с `NullReferenceException`-ом:
```C#
class ClassWithDictionary
{
    public Dictionary<string, string> Dictionary { get; set; }
}
// Trying to serialize new ClassWithDictionary() throws NRE
```

2019-07-24 09:27 UTC, sivukhin commented on Catalogue.XmlSerializer/Writing/ContentWriters/ArrayValueWriter.cs
> +                var itemValueWriter = new ArrayItemValueWriter(xmlElementInfo, itemContentWriter, i);
Может просто выпилить `ArrayItemValueWriter` и заинлайнить его код сюда?

2019-07-24 09:27 UTC, Umqra commented on Catalogue.XmlSerializer/Writing/ReportWriter.cs
> +                Write(data, skipEmpty ? new CollapseWriter(innerWriter) : (IWriter)innerWriter);
Получается `skipEmpty` также влияет на то, как сериализуются атрибуты XML-узлов? Это норм?
Может зафиксировать это поведение в тестах?

2019-08-01 13:41 UTC, fakefeik commented on Catalogue.XmlSerializer/Writing/ContentWriters/ValueWriterBase.cs
> +            WriteNonNullableValue(value, writer);
вернул обратно

2019-08-01 13:42 UTC, fakefeik commented on Catalogue.XmlSerializer/Writing/ContentWriters/ArrayValueWriter.cs
> +                var itemValueWriter = new ArrayItemValueWriter(xmlElementInfo, itemContentWriter, i);
заинлайнил

2019-08-01 13:44 UTC, fakefeik commented on Catalogue.XmlSerializer/Writing/ReportWriter.cs
> +                Write(data, skipEmpty ? new CollapseWriter(innerWriter) : (IWriter)innerWriter);
поведение зафиксировал, но добавлять такое поведение не планировал. В идеале хотелось бы поменять поведение только для элементов массива, но я пока не понял как это сделать

2019-08-08 07:24 UTC, sivukhin approved these changes

2019-08-21 06:08 UTC, merged